### ISSUE TITLE
wear切断時のcrash

### ISSUE THREAD

**Issue by alterakey** [android-saitama/abc2015s-omikuji#6]
E/AndroidRuntime(13794): FATAL EXCEPTION: main
E/AndroidRuntime(13794): Process: com.antama.abc2015s.omikuji, PID: 13794
E/AndroidRuntime(13794): java.lang.RuntimeException: Unable to start service com.antama.abc2015s.omikuji.MainService@f7b9bb9 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
E/AndroidRuntime(13794):    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2911)
E/AndroidRuntime(13794):    at android.app.ActivityThread.access$2100(ActivityThread.java:151)
E/AndroidRuntime(13794):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
E/AndroidRuntime(13794):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(13794):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(13794):    at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(13794):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13794):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(13794):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(13794):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(13794): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
E/AndroidRuntime(13794):    at com.antama.abc2015s.omikuji.MainService.onStartCommand(MainService.java:59)
E/AndroidRuntime(13794):    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
E/AndroidRuntime(13794):    ... 9 more
W/ResourceType( 1909): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 1909): Failure retrieving resources for com.google.android.apps.fitness: Resource ID #0x0
W/art     ( 1781): Suspending all threads took: 14.709ms
I/art     ( 1781): Background sticky concurrent mark sweep GC freed 10663(601KB) AllocSpace objects, 0(0B) LOS objects, 6% free, 10MB/11MB, paused 17.669ms total 126.953ms
I/Process (13794): Sending signal. PID: 13794 SIG: 9

**Comment by alterakey** [comment]
もう一つのケース

07-19 11:55:35.620  14216-14216/com.antama.abc2015s.omikuji E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.antama.abc2015s.omikuji, PID: 14216
    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at com.antama.abc2015s.omikuji.MainService$SensorAction$2.onResult(MainService.java:146)
            at com.antama.abc2015s.omikuji.MainService$SensorAction$2.onResult(MainService.java:143)
            at com.google.android.gms.common.api.a$c.b(Unknown Source)
            at com.google.android.gms.common.api.a$c.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by alterakey** [comment]
両者ともに修正。
